language: node_js
node_js:
  - 0.8
git:
  depth: 5
env:
  global:
    - X_SENCHA_CMD_VERSION="6.2.0"
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "B9sq+vmP9wrGVAccrfcw0O1COJ4xPCDvCWxAD+StDulLfezD0/m2u0PyvToFh73larr9I9T9MJ+KA7cR2QFvD3O28Qtts/drULCc0S15SQTy+Q3BkXk0ztjPq4zn+TFgAU//rYODgUGoFO10TtQdUKtH1K4S9gM6EQ7P1IawTfjbdG1rNn7qMUdDP5aPQObu9bS+0CWfOoNtX4ttnVzo5qeGwgnJkvloOTYnbS51Ur5Pn5XpY1FPMOujq7Cxrp2/l7RYLO6oKKz8XXHQBWZtBNzn2WOo0rMpGIj8sxa5SZnEDI/SwD51bslCe7suCePvhPjVsrtMDVkOIx4C9wSYVudEqUPxRA9zFYM5PuLHZ00ues/28YfhJzFYVaDc/BkXubbAx5cjSSLFW+3dcEn/sQODnLuLcQp5MGYy3Z/atylk8aSzQQJGqAnnxc51NpmBva0gWKhl+ldfqQ1cV/Sg8xWzj/Jz+LfOYrw38MB2j9icOaIWQVKK2Un/3M7asFOzBAuhqUsd580sjDzsDQnlF4pwSZQkTyVaOrl/Aby4Q+GTm38thJ34XMZbWHBT7m8Dp8WIlmyWS1gutUihegDbv+b1sOxOkVsWFDSfaXp3pmcBGnLkMBgnqSYnhvlR670Z9zFrBBHCG9Se1/jAUSiFT9P1aVaWmcLVjWUtBArMwIs="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  # Framebuffer for Firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Install JSDuck dependency
  - "gem install jsduck"
  # Install Sencha Cmd
  - "wget http://cdn.sencha.com/cmd/$X_SENCHA_CMD_VERSION/no-jre/SenchaCmd-$X_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "unzip SenchaCmd-$X_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "chmod +x SenchaCmd-$X_SENCHA_CMD_VERSION.*-linux-amd64.sh"
  - "./SenchaCmd-$X_SENCHA_CMD_VERSION.*-linux-amd64.sh -q -dir ~/bin/Sencha/Cmd/$X_SENCHA_CMD_VERSION"
  # Make Sencha Cmd and CoffeeScript available in the PATH
  - "export PATH=~/bin/Sencha/Cmd/$X_SENCHA_CMD_VERSION/:$TRAVIS_BUILD_DIR/node_modules/karma/bin:$TRAVIS_BUILD_DIR/node_modules/coffee-script/bin:$PATH"
  # Change directory to the package and build the package
  - "cd $TRAVIS_BUILD_DIR/JukolaApp && sencha app clean && sencha app refresh && sencha app build"
  # Change directory back to the root of the repository ready for running tests
  - "cd $TRAVIS_BUILD_DIR"

addons:
  coverity_scan:
    project:
      name: "ikettu/JukolaTest"
    notification_email: ikettu@gmail.com
    build_command_prepend: ""
    build_command:   "--no-command --fs-capture-search JukolaApp/"
    branch_pattern: coverity_scan
    
deploy:
  provider: s3
  access_key_id: "AKIAJWVD6C3522MIUEVA"
  secret_access_key:
    secure: "ox2SqEdIRmro3/J6lL6UfQoefvkJtsiX8c1bhdEnV1Yygid09tETV88AvxQf49zKEvB2FdzhldVzO9sfK1XFTWWNC0BniO4FoDvTFgdfv98UtwSRLHrrZJ2wsB9pSVRwcKsgsqVSXK4LkojuSkrShyJ3VYdLy5JVgeQLgLVJtSxks0szduFsiSDIgHDpFS3y+FGjznZ7xswnsjWGu5Ig34fiuME52w/E0zG9YeI4+4s8fTqAesrd9966bQcBaiq2xUbWcnsDdh4XBREjSt8m0D5GsyUHxBe2TsSNG634kiKd1ur34jU6kSHnq1GgC3nba4BJVuNrrz3N1i9gedj90Y5eIlFvCeKIlR/5XVU/g836iO8T4NmO99NhXfbRrkkFUUe5s1fTeYCkzOSDtXCHhtOKSxyntBAQaFEAMySiAzpU53hmafBLD4t6KtJ18tgyo/L0dKH7CrQozc1zkkqZkLuWmy5DXJFzVc59670j1Krqdj14eA6a+uqDSves83pvRKd5O7EjzSeavu5QC6oTkqMiUPsP4ZL2pLY8hlJmRzdDM+R9RKi2hh0lOca7ZGHJv8D49FzgzT72wkUYH5dWLLmICgFa2qeW7SR06O92U5QCTT3LuBLpHYQL3i3T8JLjrn+tu5G0TjnuMyWr4vcKxWQrDrTXOgaLU/voq/K5bMo="
  bucket: "jukolatest"
  region: eu-west-1
  skip_cleanup: true
  local_dir: build/production/JukolaApp
  default_text_charset: "utf-8"
  cache_control: "no-cache"
  on:
    branch: master