language: node_js
node_js:
  - 0.8
env:
  - X_SENCHA_CMD_VERSION="6.1.3"
before_script:
  # Framebuffer for Firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Install JSDuck dependency
  - "gem install jsduck"
  # Download, unzip and symlink Sencha Ext JS dependency
  #- "wget http://cdn.sencha.com/ext/commercial/ext-4.2.1-commercial.zip"
  #- "unzip -q ext-4.2.1-commercial.zip"
  #- "ln -sv `pwd`/ext-4.2.1.883 $TRAVIS_BUILD_DIR/../ext"
  # Install Sencha Cmd
  #http://cdn.sencha.com/cmd/6.1.3/no-jre/SenchaCmd-6.1.3-linux-amd64.sh.zip
  - "wget http://cdn.sencha.com/cmd/$X_SENCHA_CMD_VERSION/no-jre/SenchaCmd-$X_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "unzip -q SenchaCmd-$X_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "chmod +x SenchaCmd-$X_SENCHA_CMD_VERSION-linux-amd64.sh"
  - "./SenchaCmd-$X_SENCHA_CMD_VERSION-linux-amd64.sh --mode unattended"
  # Make Sencha Cmd and CoffeeScript available in the PATH
  - "export PATH=~/bin/Sencha/Cmd/$X_SENCHA_CMD_VERSION/:$TRAVIS_BUILD_DIR/node_modules/karma/bin:$TRAVIS_BUILD_DIR/node_modules/coffee-script/bin:$PATH"
  # Change directory to the package and build the package
  - "cd $TRAVIS_BUILD_DIR/JukolaApp && sencha app build"
  # Change directory back to the root of the repository ready for running tests
  - "cd $TRAVIS_BUILD_DIR"
